services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: back-moudsound:latest
    container_name: moudsound-backend
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PORT=${PORT:-8000}
      - IN_PROD=${IN_PROD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SITE_DOMAIN=${SITE_DOMAIN}
      - SITE_NAME=${SITE_NAME}
    depends_on:
      - db
    networks:
      - internal

  db:
    container_name: moudsound-db
    image: postgres:13
    volumes:
      - moudsound-pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5436:${POSTGRES_PORT:-5432}"
    networks:
      - internal

volumes:
  moudsound-pgdata:

networks:
  internal:
    driver: bridge
